import PropsImg from "../types/propsImg";

export const LIST_IMG: PropsImg[] = [
    {
      alt:"string",
      img:"/image/1.jpg",
    },
    {
      alt:"string",
      img:"/image/2.jpg",
    },
    {
      alt:"string",
      img:"/image/3.png",
    },
    {
      alt:"string",
      img:"/image/4.jpg",
    },
    {
      alt:"string",
      img:"/image/5.jfif",
    },
    {
      alt:"string",
      img:"/image/6.jfif",
    },
    {
      alt:"string",
      img:"/image/7.jfif",
    },
    {
      alt:"string",
      img:"/image/8.jfif",
    },
    {
      alt:"string",
      img:"/image/9.png",
    },
    {
      alt:"string",
      img:"/image/10.png",
    },
  ];